/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.proyecto.Vistas;

import com.proyecto.Administrador.ArregloAdministradores;
import com.proyecto.Foro.Mensaje;
import com.proyecto.Foro.Tema;
import com.proyecto.Nodos.NodoRespuesta;
import com.proyecto.Otros.Formatos;
import com.proyectoUsuario.ListaEnlazadaDobleUsuarios;
import com.proyectoUsuario.Usuario;
import java.awt.Color;
import java.awt.Dimension;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.text.StyledDocument;

/**
 *
 * @author ALE
 */
public class ForoVent extends javax.swing.JFrame {

    com.proyecto.Foro.Foro foro = new com.proyecto.Foro.Foro();
    Usuario usuarioActual = null;
    ListaEnlazadaDobleUsuarios listaUsuarios = new ListaEnlazadaDobleUsuarios();

    public ForoVent() {
        initComponents();
        jPanel3.setVisible(false);
        this.setSize(new Dimension(1200, 751));
        foro.cargarTemas();
        listaUsuarios.loadUser();

    }

    public ForoVent(Usuario usuarioActual) {
        this();
        this.usuarioActual = usuarioActual;
        user.setText(usuarioActual.getUsuario());

    }

    private void mostrarC() {
        String contenido = "";

        for (Tema tema : foro.getTemas()) {
            contenido += tema + "\n\n";
        }

        jPanel3.setVisible(true);

        contenido = contenido.replaceAll("\u001B\\[[;\\d]*m", "");

        // Reemplazar las etiquetas <br> por saltos de línea estándar
        contenido = contenido.replaceAll("<br>", "\n");

        jTextPane1.setForeground(Color.WHITE);// Asegurarse de que el texto se muestre desde el principio
        jTextPane1.setEditable(false);
        jTextPane1.setText(contenido);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        boton_verforo = new javax.swing.JButton();
        btn_anadirtema = new javax.swing.JButton();
        btn_mensaje = new javax.swing.JButton();
        btn_respuesta = new javax.swing.JButton();
        btn_buscar = new javax.swing.JButton();
        btn_filtrar = new javax.swing.JButton();
        btn_eliminartema = new javax.swing.JButton();
        btn_eliminarmensaje = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();
        btn_elimianrcoemntario = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        user = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0,0,0,80));

        boton_verforo.setBackground(new java.awt.Color(0, 0, 0));
        boton_verforo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        boton_verforo.setForeground(new java.awt.Color(204, 0, 204));
        boton_verforo.setText("Ver foro");
        boton_verforo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_verforoActionPerformed(evt);
            }
        });

        btn_anadirtema.setBackground(new java.awt.Color(0, 0, 0));
        btn_anadirtema.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_anadirtema.setForeground(new java.awt.Color(153, 0, 255));
        btn_anadirtema.setText("Añadir tema");
        btn_anadirtema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_anadirtemaActionPerformed(evt);
            }
        });

        btn_mensaje.setBackground(new java.awt.Color(0, 0, 0));
        btn_mensaje.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_mensaje.setForeground(new java.awt.Color(255, 153, 0));
        btn_mensaje.setText("Añadir mensaje");
        btn_mensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mensajeActionPerformed(evt);
            }
        });

        btn_respuesta.setBackground(new java.awt.Color(0, 0, 0));
        btn_respuesta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_respuesta.setForeground(new java.awt.Color(0, 255, 204));
        btn_respuesta.setText("Realizar comentario");
        btn_respuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_respuestaActionPerformed(evt);
            }
        });

        btn_buscar.setBackground(new java.awt.Color(0, 0, 0));
        btn_buscar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_buscar.setForeground(new java.awt.Color(204, 204, 0));
        btn_buscar.setText("Buscar en el foro");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        btn_filtrar.setBackground(new java.awt.Color(0, 0, 0));
        btn_filtrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_filtrar.setForeground(new java.awt.Color(255, 0, 153));
        btn_filtrar.setText("Filtrar por autor");
        btn_filtrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_filtrarActionPerformed(evt);
            }
        });

        btn_eliminartema.setBackground(new java.awt.Color(0, 0, 0));
        btn_eliminartema.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_eliminartema.setForeground(new java.awt.Color(153, 255, 0));
        btn_eliminartema.setText("Eliminar tema");
        btn_eliminartema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminartemaActionPerformed(evt);
            }
        });

        btn_eliminarmensaje.setBackground(new java.awt.Color(0, 0, 0));
        btn_eliminarmensaje.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_eliminarmensaje.setForeground(new java.awt.Color(255, 153, 153));
        btn_eliminarmensaje.setText("Eliminar mensaje");
        btn_eliminarmensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarmensajeActionPerformed(evt);
            }
        });

        btn_salir.setBackground(new java.awt.Color(0, 0, 0));
        btn_salir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_salir.setForeground(new java.awt.Color(0, 204, 204));
        btn_salir.setText("Salir del foro");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        btn_elimianrcoemntario.setBackground(new java.awt.Color(0, 0, 0));
        btn_elimianrcoemntario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_elimianrcoemntario.setForeground(new java.awt.Color(255, 51, 0));
        btn_elimianrcoemntario.setText("Eliminar comentario");
        btn_elimianrcoemntario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_elimianrcoemntarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_elimianrcoemntario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_eliminarmensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_eliminartema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_filtrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_buscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_respuesta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_mensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_anadirtema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boton_verforo, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addComponent(boton_verforo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_anadirtema, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_respuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_filtrar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_eliminartema, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_eliminarmensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_elimianrcoemntario, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 300, 540));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0,80));
        jPanel3.setEnabled(false);

        jTextPane1.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(jTextPane1);

        user.setBackground(new java.awt.Color(0, 0, 0));
        user.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        user.setForeground(new java.awt.Color(255, 255, 255));
        user.setFocusable(false);

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Usuario actual");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 776, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 810, 540));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fr (1).png"))); // NOI18N
        jLabel2.setText("vvcvcv");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_filtrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_filtrarActionPerformed
        String autorX = JOptionPane.showInputDialog("Ingrese el nombre del autor a filtrar:");

        if (autorX != null && !autorX.trim().isEmpty()) {
            boolean encontrado = false;
            StringBuilder mensajesAutor = new StringBuilder();

            for (Tema tema : foro.getTemas()) {
                for (Mensaje mensaje : tema.obtenerMensajes()) {
                    if (mensaje.getAutor().equalsIgnoreCase(autorX)) {
                        mensajesAutor.append(mensaje.toString()).append("\n");
                        encontrado = true;
                    }
                    NodoRespuesta actual = mensaje.getRespuestas(); // Obtiene el primer nodo de la lista enlazada
                    while (actual != null) {
                        Mensaje respuesta = actual.getRespuesta(); // Obtiene el mensaje dentro del nodo
                        if (respuesta.getAutor().equalsIgnoreCase(autorX)) {
                            mensajesAutor.append(respuesta.toString()).append("\n");
                            encontrado = true;
                        }
                        actual = actual.getSiguiente(); // Avanza al siguiente nodo
                    }
                }
            }

            if (encontrado) {
                String mensajesFormateados = Formatos.limpiarFormatoConsola(mensajesAutor.toString());
                JOptionPane.showMessageDialog(null, mensajesFormateados, "Mensajes del Autor: " + autorX, JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "No se encontraron mensajes del autor: " + autorX, "Error", JOptionPane.ERROR_MESSAGE);
            }

            mostrarC();
        } else {
            JOptionPane.showMessageDialog(null, "Operación cancelada o entrada vacía.");
        }

    }//GEN-LAST:event_btn_filtrarActionPerformed

    private void boton_verforoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_verforoActionPerformed

        mostrarC();

    }//GEN-LAST:event_boton_verforoActionPerformed

    private void btn_anadirtemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_anadirtemaActionPerformed
        String titulo = JOptionPane.showInputDialog("Ingrese el título del nuevo tema:");
        if (titulo == null || titulo.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Operación cancelada o título vacío.");

        } else if (foro.crearTema(titulo, usuarioActual.getUsuario())) {
            JOptionPane.showMessageDialog(this, "Tema creado exitosamente.");
        } else {
            JOptionPane.showMessageDialog(this, "El tema con el título \"" + titulo + "\" ya existe.", "Error",
                    JOptionPane.ERROR_MESSAGE);

        }
        mostrarC();
    }//GEN-LAST:event_btn_anadirtemaActionPerformed

    private void btn_mensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mensajeActionPerformed

        String inputIdTema = JOptionPane.showInputDialog("Ingrese el número del tema al que desea agregar un mensaje:");

        if (inputIdTema != null && !inputIdTema.trim().isEmpty()) {
            try {
                int idTema = Integer.parseInt(inputIdTema);

                String contenido = JOptionPane.showInputDialog("Ingrese su mensaje:");
                if (contenido != null && !contenido.trim().isEmpty()) {
                    foro.aMensaje(idTema, usuarioActual.getUsuario(), contenido);
                    mostrarC();
                    JOptionPane.showMessageDialog(null, "Mensaje agregado con éxito.");
                } else {
                    JOptionPane.showMessageDialog(null, "Operación cancelada o mensaje vacío.");
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Ingrese un número válido para el ID del tema.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Operación cancelada o entrada inválida.");
        }


    }//GEN-LAST:event_btn_mensajeActionPerformed

    private void btn_respuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_respuestaActionPerformed

        String inputIdTema = JOptionPane.showInputDialog("Ingrese el número del tema al que desea dejar un comentario:");

        if (inputIdTema != null && !inputIdTema.trim().isEmpty()) {
            try {
                int idTema = Integer.parseInt(inputIdTema);

                String inputNumMensaje = JOptionPane.showInputDialog("Ingresa el número del mensaje a comentar:");
                if (inputNumMensaje != null && !inputNumMensaje.trim().isEmpty()) {
                    try {
                        int numMensaje = Integer.parseInt(inputNumMensaje);

                        String contenido = JOptionPane.showInputDialog("Ingrese el comentario:");
                        if (contenido != null && !contenido.trim().isEmpty()) {
                            if (foro.responderMensaje(idTema, numMensaje, usuarioActual.getUsuario(), contenido)) {
                                mostrarC();
                                JOptionPane.showMessageDialog(null, "Comentario agregado con éxito.");
                            }

                        } else {
                            JOptionPane.showMessageDialog(null, "Operación cancelada o comentario vacío.");
                        }
                    } catch (NumberFormatException e) {
                        JOptionPane.showMessageDialog(null, "Ingrese un número válido para el mensaje.");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Operación cancelada o entrada inválida para el número de mensaje.");
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Ingrese un número válido para el ID del tema.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Operación cancelada o entrada inválida para el ID del tema.");
        }

    }//GEN-LAST:event_btn_respuestaActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed

        String palabraClave = JOptionPane.showInputDialog("Ingrese la palabra clave para buscar en el foro:");

        if (palabraClave != null && !palabraClave.trim().isEmpty()) {
            foro.buscarPorPalabraClave(palabraClave);
            mostrarC();
        } else {
            JOptionPane.showMessageDialog(null, "Operación cancelada o entrada vacía.");
        }

    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_eliminartemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminartemaActionPerformed

        String inputIdB = JOptionPane.showInputDialog("ID del tema:");

        if (inputIdB != null && !inputIdB.trim().isEmpty()) {
            int idB = Integer.parseInt(inputIdB);
            foro.deleteTema(idB, usuarioActual.getUsuario());
        } else {
            JOptionPane.showMessageDialog(null, "Operación cancelada o entrada inválida.");
        }
        mostrarC();

    }//GEN-LAST:event_btn_eliminartemaActionPerformed

    private void btn_eliminarmensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarmensajeActionPerformed

        try {
            String inputIdBu = JOptionPane.showInputDialog("ID del tema:");

            if (inputIdBu != null && !inputIdBu.trim().isEmpty()) {
                int idBu = Integer.parseInt(inputIdBu);

                String inputNumE = JOptionPane.showInputDialog("ID del mensaje:");
                if (inputNumE != null && !inputNumE.trim().isEmpty()) {
                    int numE = Integer.parseInt(inputNumE);
                    foro.eliminarMensaje(idBu, numE, usuarioActual.getUsuario());
                } else {
                    JOptionPane.showMessageDialog(null, "Operación cancelada o entrada inválida.");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Operación cancelada o entrada inválida.");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Error: Debe ingresar un número válido.", "Entrada inválida", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocurrió un error inesperado: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

        mostrarC();

    }//GEN-LAST:event_btn_eliminarmensajeActionPerformed

    private void btn_elimianrcoemntarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_elimianrcoemntarioActionPerformed

        try {
            String inputIdBus = JOptionPane.showInputDialog("ID del tema:");

            if (inputIdBus != null && !inputIdBus.trim().isEmpty()) {
                int idBus = Integer.parseInt(inputIdBus);

                String inputNumMen = JOptionPane.showInputDialog("ID del mensaje:");
                if (inputNumMen != null && !inputNumMen.trim().isEmpty()) {
                    int numMen = Integer.parseInt(inputNumMen);

                    String inputNumR = JOptionPane.showInputDialog("ID del comentario:");
                    if (inputNumR != null && !inputNumR.trim().isEmpty()) {
                        int numR = Integer.parseInt(inputNumR);

                        // Aquí puedes agregar la función que usará los valores obtenidos
                        foro.eliminarRespuesta(idBus, numMen, numR, usuarioActual.getUsuario());
                        mostrarC();
                    } else {
                        JOptionPane.showMessageDialog(null, "Operación cancelada o entrada inválida.");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Operación cancelada o entrada inválida.");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Operación cancelada o entrada inválida.");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Error: Debe ingresar un número válido.", "Entrada inválida", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocurrió un error inesperado: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btn_elimianrcoemntarioActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        MenuUsuario menu = new MenuUsuario(usuarioActual);
        menu.setVisible(true);
        menu.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btn_salirActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_verforo;
    private javax.swing.JButton btn_anadirtema;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_elimianrcoemntario;
    private javax.swing.JButton btn_eliminarmensaje;
    private javax.swing.JButton btn_eliminartema;
    private javax.swing.JButton btn_filtrar;
    private javax.swing.JButton btn_mensaje;
    private javax.swing.JButton btn_respuesta;
    private javax.swing.JButton btn_salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
